/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager */

#ifndef _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager
#define _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager_connect
  (JNIEnv *, jobject);

/*
 * Class:     com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinPeerManager_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
