/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_jni_Bip39 */

#ifndef _Included_com_breadwallet_crypto_core_jni_Bip39
#define _Included_com_breadwallet_crypto_core_jni_Bip39
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_jni_Bip39
 * Method:    deriveKey
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_breadwallet_crypto_core_jni_Bip39_deriveKey
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
