/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWallet */

#ifndef _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWallet
#define _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWallet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWallet
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWallet_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
