/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinMasterPubKey */

#ifndef _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinMasterPubKey
#define _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinMasterPubKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinMasterPubKey
 * Method:    createBitcoinMasterPubKey
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinMasterPubKey_createBitcoinMasterPubKey
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
