/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWalletManagerClient */

#ifndef _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWalletManagerClient
#define _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinWalletManagerClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
