/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_common_jni_JniReference */

#ifndef _Included_com_breadwallet_crypto_core_common_jni_JniReference
#define _Included_com_breadwallet_crypto_core_common_jni_JniReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_common_jni_JniReference
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_breadwallet_crypto_core_common_jni_JniReference_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
