/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinChainParams */

#ifndef _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinChainParams
#define _Included_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinChainParams
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinChainParams
 * Method:    createTestnetChainParams
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_breadwallet_crypto_core_bitcoin_jni_CoreBitcoinChainParams_createTestnetChainParams
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
